sudo: False

language: python

env:
  - PRECEDENCE='default'
  - PRECEDENCE='default bleeding'

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda
  - conda install pip
  - conda install xonsh pyyaml lazyasd
  - pip install xonda

script:
  - set -e
  - python setup.py install
  # Install dependencies
  - orch score.yaml

notifications:
  email: false

